// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.AutoDemo;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Spark;

public class RobotMap {
	
    public static final int driveMotorLeft = 2; // 2
	public static final int driveMotorLeft_Back = 3; //3
	public static final int driveMotorRight = 0; //0
	public static final int driveMotorRight_Back = 1; //1
	
	public static Spark gearFlipSpark1;
	
    public static AnalogGyro sensorDataGyroscope1;

	public static final int driveMotorLeftDir = -1; //-1
	public static final int driveMotorRightDir = 1; //1
	public static final int driveMotorRightBackDir = 1; //1
	public static final int driveMotorLeftBackDir = -1; //-1

    public static void init() {
    	
        gearFlipSpark1 = new Spark(4);
        LiveWindow.addActuator("GearFlip", "Spark 1", (Spark) gearFlipSpark1);

        sensorDataGyroscope1 = new AnalogGyro(0);
        LiveWindow.addSensor("SensorData", "Gyroscope 1", sensorDataGyroscope1);
    }
}
