// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.AutoDemo.subsystems;

import org.usfirst.frc253.AutoDemo.RobotMap;

import edu.wpi.first.wpilibj.AnalogGyro;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class SensorData extends Subsystem {
	
    public final AnalogGyro gyro = RobotMap.sensorDataGyroscope1;

    public void initDefaultCommand() {}
}

